-- Run this once in Supabase SQL Editor
create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  phone text not null,
  request_type text not null,
  details text,
  source text default 'larak.store',
  page_url text,
  language text default 'ar',
  status text not null default 'new'
);

alter table public.service_requests enable row level security;

drop policy if exists "Public can submit service requests" on public.service_requests;
create policy "Public can submit service requests"
on public.service_requests
for insert
to anon, authenticated
with check (true);

-- No public SELECT policy is created.
-- This means website visitors can submit requests but cannot read other requests.
